[package]
name = "open-in-mpv"
version = "0.1.0"
authors = ["Leonardo Baldin <leobaldin.2000@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
build = false

[dependencies]
percent-encoding = "1.0.1"
url = "1.7.2"

[build-dependencies]
byteorder = "1.3.2"
openssl = "0.10.23"